export const productsData = [
    {
        id: "p1",
        name: "Drift Low Sneaker",
        category: "Footwear",
        price: 148,
        rating: 4.8,
        reviews: 214,
        image: "img/product-1.jpg",
        badge: "New",
        bg: "bg-footwear",
        desc: "Engineered for maximum comfort and durability. The Drift Low features our proprietary sole technology for urban exploration and a minimalist aesthetic."
    },
    {
        id: "p2",
        name: "Cloud Parka",
        category: "Outerwear",
        price: 295,
        rating: 4.9,
        reviews: 87,
        image: "img/product-6.jpg",
        badge: null,
        bg: "bg-outerwear",
        desc: "A heavyweight piece built for unpredictable weather. Water-resistant outer shell with ethically sourced insulation for the ultimate winter protection."
    },
    {
        id: "p3",
        name: "Trail Pack 22L",
        category: "Accessories",
        price: 189,
        rating: 4.7,
        reviews: 156,
        image: "img/product-3.jpg",
        badge: null,
        bg: "bg-accessories",
        desc: "Designed for seamless transition from the commute to the trail. Features a weather-proof laptop compartment and tactical mounting points."
    },
    {
        id: "p4",
        name: "Merino Crew Tee",
        category: "Tops",
        price: 68,
        originalPrice: 89,
        rating: 4.6,
        reviews: 403,
        image: "img/product-4.jpg",
        badge: "Sale",
        bg: "bg-essentials",
        desc: "The ultimate base layer. Crafted from ultrafine merino wool for natural temperature regulation and a premium drape."
    },
    {
        id: "p5",
        name: "Slim Cargo Pants",
        category: "Tops",
        price: 178,
        rating: 4.5,
        reviews: 92,
        image: "img/product-5.jpg",
        badge: null,
        bg: "bg-essentials",
        desc: "Technical fabric combined with articulated patterning for unrestricted movement. Multiple low-profile pockets for utility without bulk."
    },
    {
        id: "p6",
        name: "Micro Fleece Zip",
        category: "Outerwear",
        price: 124,
        rating: 4.8,
        reviews: 311,
        image: "img/product-14.jpg",
        badge: "Low Stock",
        bg: "bg-outerwear",
        desc: "Lightweight warmth with a technical face. Perfect as a standalone piece for cool evenings or layered under a shell for harsh conditions."
    },
    {
        id: "p7",
        name: "Grip Slides",
        category: "Footwear",
        price: 85,
        rating: 4.4,
        reviews: 178,
        image: "img/product-7.jpg",
        badge: null,
        bg: "bg-footwear",
        desc: "Recovery footwear redefined. Features an aggressive tread pattern for indoor/outdoor use and a high-density foam footbed."
    },
    {
        id: "p8",
        name: "Urban Cap",
        category: "Accessories",
        price: 52,
        rating: 4.7,
        reviews: 629,
        image: "img/product-8.jpg",
        badge: null,
        bg: "bg-accessories",
        desc: "Classic 6-panel design updated with technical weather-resistant fabrics and an adjustable laser-cut strap."
    },
    {
        id: "p9",
        name: "Apex Shell Jacket",
        category: "Outerwear",
        price: 340,
        rating: 4.9,
        reviews: 124,
        image: "img/product-9.jpg",
        badge: "Pro",
        bg: "bg-outerwear",
        desc: "Our most advanced shell yet. 3-layer waterproof membrane with fully taped seams and laser-cut ventilation."
    },
    {
        id: "p10",
        name: "Core Heavy Hoodie",
        category: "Tops",
        price: 120,
        rating: 4.7,
        reviews: 512,
        image: "img/product-10.jpg",
        badge: "Best Seller",
        bg: "bg-essentials",
        desc: "A structural masterpiece. 500GSM heavyweight cotton fleece with a structured hood and oversized fit."
    },
    {
        id: "p11",
        name: "Versa Tote Bag",
        category: "Accessories",
        price: 95,
        rating: 4.5,
        reviews: 89,
        image: "img/product-11.jpg",
        badge: null,
        bg: "bg-accessories",
        desc: "Tactical utility meets everyday carry. Durable Cordura fabric with modular attachment points and magnetic closures."
    },
    {
        id: "p12",
        name: "Nova Runner",
        category: "Footwear",
        price: 165,
        rating: 4.8,
        reviews: 143,
        image: "img/product-12.jpg",
        badge: "New",
        bg: "bg-footwear",
        desc: "Hyper-responsive cushioning for high-intensity movement. Breathable mesh upper with reflective accents."
    },
    {
        id: "p13",
        name: "Technical Crew",
        category: "Tops",
        price: 75,
        rating: 4.6,
        reviews: 211,
        image: "img/product-13.jpg",
        badge: null,
        bg: "bg-essentials",
        desc: "Advanced moisture-wicking technology designed to keep you warm in sub-zero temperatures without sacrificing breathability."
    },
    {
        id: "p14",
        name: "Storm Vest",
        category: "Outerwear",
        price: 180,
        rating: 4.7,
        reviews: 64,
        image: "img/product-14.jpg",
        badge: null,
        bg: "bg-outerwear",
        desc: "The perfect mid-layer for erratic transitions. Windproof chest panels with a high-stretch breathable back."
    },
    {
        id: "p15",
        name: "Knit Beanie",
        category: "Accessories",
        price: 45,
        rating: 4.8,
        reviews: 842,
        image: "img/product-15.jpg",
        badge: "Essential",
        bg: "bg-accessories",
        desc: "Soft merino wool blend with a classic folded cuff. Designed to retain heat while remaining comfortable all day."
    },
    {
        id: "p17",
        name: "Grid Polo",
        category: "Tops",
        price: 85,
        rating: 4.6,
        reviews: 128,
        image: "img/product-17.jpg",
        badge: null,
        bg: "bg-essentials",
        desc: "Technical piqué fabric with a contemporary zipper placket. Minimalist branding for a clean, sharp aesthetic."
    }
];
